"""
open_pr.py
Week 4: Open a GitHub PR proposing the least-privilege policy for each
high/medium risk role as a file diff in the repo.

Requires:
  - GITHUB_TOKEN env var with repo write access
  - GITHUB_REPO env var in format "owner/repo"
  - data/policies/ generated by generate_policies.py

Usage:
  export GITHUB_TOKEN=ghp_...
  export GITHUB_REPO=sandhyayadavalli/iam-least-privilege-engine
  python3 scripts/open_pr.py
"""

import json
import os
import base64
from datetime import datetime, timezone
import urllib.request
import urllib.error

POLICIES_DIR = os.path.join("data", "policies")
SUMMARY_PATH = os.path.join(POLICIES_DIR, "summary.json")

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "")
BASE_BRANCH = "main"


def gh_request(method, path, body=None):
    url = f"https://api.github.com/repos/{GITHUB_REPO}{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        print(f"  GitHub API error {e.code}: {e.read().decode()}")
        return None


def get_base_sha():
    resp = gh_request("GET", f"/git/ref/heads/{BASE_BRANCH}")
    return resp["object"]["sha"] if resp else None


def create_branch(branch_name, base_sha):
    return gh_request(
        "POST",
        "/git/refs",
        {"ref": f"refs/heads/{branch_name}", "sha": base_sha},
    )


def upsert_file(branch, file_path, content, message):
    """Create or update a file on the branch."""
    encoded = base64.b64encode(content.encode()).decode()
    # Check if file already exists (to get its SHA for update)
    existing = gh_request("GET", f"/contents/{file_path}?ref={branch}")
    body = {
        "message": message,
        "content": encoded,
        "branch": branch,
    }
    if existing and "sha" in existing:
        body["sha"] = existing["sha"]
    return gh_request("PUT", f"/contents/{file_path}", body)


def create_pr(branch_name, title, body):
    return gh_request(
        "POST",
        "/pulls",
        {
            "title": title,
            "body": body,
            "head": branch_name,
            "base": BASE_BRANCH,
        },
    )


def build_pr_body(roles):
    lines = [
        "## IAM Least-Privilege Policy Proposals",
        "",
        "Auto-generated by the IAM Least-Privilege Engine based on CloudTrail usage analysis.",
        "",
        "### Summary",
        "",
        "| Role | Risk | Used Actions | Reduction |",
        "|---|---|---|---|",
    ]
    for r in roles:
        dormant = " (DORMANT)" if r["is_dormant"] else ""
        lines.append(
            f"| `{r['role_name']}` | {r['risk_level']} | "
            f"{r['used_action_count']} | -{r['reduction_pct']:.0f}%{dormant} |"
        )
    lines += [
        "",
        "### What changed",
        "Each file under `proposed_policies/` contains a least-privilege IAM policy",
        "built from only the actions observed in CloudTrail over the last 90 days.",
        "Dormant roles (zero observed usage) receive a Deny-all policy.",
        "",
        "### Review checklist",
        "- [ ] Verify used actions match expected role behavior",
        "- [ ] Check dormant roles — are they actually unused or just not captured?",
        "- [ ] Apply policies in staging before production",
        "",
        "_Generated by [iam-least-privilege-engine](https://github.com/"
        + GITHUB_REPO
        + ")_",
    ]
    return "\n".join(lines)


def main():
    if not GITHUB_TOKEN or not GITHUB_REPO:
        print("ERROR: Set GITHUB_TOKEN and GITHUB_REPO environment variables.")
        print("  export GITHUB_TOKEN=ghp_...")
        print("  export GITHUB_REPO=youruser/iam-least-privilege-engine")
        return

    with open(SUMMARY_PATH) as f:
        summary = json.load(f)

    roles = summary["roles"]
    # Only PR for HIGH and MEDIUM risk roles
    target_roles = [r for r in roles if r["risk_level"] in ("HIGH", "MEDIUM")]

    print(f"Opening PR for {len(target_roles)} HIGH/MEDIUM risk roles...\n")

    base_sha = get_base_sha()
    if not base_sha:
        print("Could not get base branch SHA. Check GITHUB_REPO and GITHUB_TOKEN.")
        return

    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    branch_name = f"iam-least-privilege-{ts}"

    print(f"Creating branch: {branch_name}")
    create_branch(branch_name, base_sha)

    for role in target_roles:
        role_name = role["role_name"]
        policy_file = os.path.join(POLICIES_DIR, f"{role_name}.json")
        with open(policy_file) as f:
            policy_content = f.read()

        dest_path = f"proposed_policies/{role_name}.json"
        print(f"  Uploading {dest_path}")
        upsert_file(
            branch_name,
            dest_path,
            policy_content,
            f"propose least-privilege policy for {role_name}",
        )

    pr_body = build_pr_body(target_roles)
    pr_title = f"IAM least-privilege proposals ({ts}) — {len(target_roles)} roles"
    print(f"\nOpening PR: {pr_title}")
    pr = create_pr(branch_name, pr_title, pr_body)

    if pr and "html_url" in pr:
        print(f"\nPR opened: {pr['html_url']}")
    else:
        print("\nPR creation failed — check output above.")


if __name__ == "__main__":
    main()
